[package]
name = "matrix-sdk-libolm-migration"
version = "0.1.0"
edition = "2021"
rust-version.workspace = true

[features]
uniffi = ["dep:uniffi"]

[dependencies]
anyhow = { workspace = true }
serde = { workspace = true }
uniffi = { workspace = true, optional = true }
matrix-sdk-crypto = { version = "0.6.0", path = "../matrix-sdk-crypto" }
thiserror = { workspace = true }
vodozemac = { workspace = true }
zeroize = { workspace = true }
ruma = { workspace = true }

[dev-dependencies]
matrix-sdk-sqlite = { path = "../matrix-sdk-sqlite", features = ["crypto-store"] }
serde = { workspace = true }
serde_json = { workspace = true }
tempfile = "3.8.1"
tokio = { workspace = true, features = ["rt", "macros"] }
